name : Docker-CI
trigger:
  branches:
    include:
      - main

variables:
  SecretConnectionToBlob: $(ConnectionToBlob)

pool:
  name: default 
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        dockerComposeFile: '**/docker-compose.yml'
        dockerComposeFileArgs: 'AzureBlobConnectionString=$(SecretConnectionToBlob)'
        action: 'Build services'
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        dockerComposeFile: '**/docker-compose.yml'
        dockerComposeFileArgs: 'AzureBlobConnectionString=$(SecretConnectionToBlob)'
        action: 'Push services'