name : Docker-CI
trigger:
  branches:
    include:
      - azure-build
 
pool:
  name: default 
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 'retur//$(Build.Repository.Name)'
        action: 'Build services'

    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'