name : Docker-CI
trigger:
  branches:
    include:
      - main
 
pool:
  name: default 
  vmImage: 'ubuntu-latest'

variables:
  Version: '$(Build.BuildId)'
  PrePath: 'retur/'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: '$(PrePath)$(Build.Repository.Name):$(Version)'
        action: 'Build services'
        serviceName: 'retur/'

    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'