name : Docker-CI
trigger:
  branches:
    include:
      - main

variables:
  Connection: Docker Hub
pool:
  name: default 
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker images
    steps:
    
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        dockerComposeFile: '**/docker-compose.yml'
        qualifyImageNames: false
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'down'
    - task: DockerCompose@0
      env:
        ConnectionToBlob: $(SecretConnectionToBlob)
        ConnectionToDB: $(DBConnection)
        SecretJWTKey: $(JWTKey)
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: '$(Connection)'
        dockerComposeFile: '**/docker-compose.yml'
        dockerComposeFileArgs: |
          ConnectionToBlob=$(SecretConnectionToBlob)
          ConnectionToDB=$(DBConnection)
          SecretJWTKey=$(JWTKey)
        projectName: 'retur//'
        qualifyImageNames: false
        action: 'Run services'

    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        command: 'tag'
        arguments: 'retur_worker retur/retur_worker:$(Build.BuildId)'

    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        command: 'tag'
        arguments: 'retur_web retur/retur_web:$(Build.BuildId)'

    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'retur/retur_web:$(Build.BuildId)'
        command: 'push'
        tags: 

    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'retur/retur_worker:$(Build.BuildId)'
        command: 'push'
        tags: 
