name : Docker-CI
trigger:
  branches:
    include:
      - main

variables:
  Connection: Docker Hub
pool:
  name: default 
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker images
    steps:
    - task: DockerCompose@0
      env:
        SecretConnectionToBlob: $(SecretConnectionToBlob)
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: '$(Connection)'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 'retur/socNet'
        qualifyImageNames: false
        action: 'Push services'
        additionalImageTags: '$(Build.BuildId)'
        arguments: 'retur/socialnetwork'
        includeSourceTags: false
        includeLatestTag: false