version: "3.9"

services:

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management-alpine
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "5672:5672"
    - "15672:15672"
    
    
  web:
    image: retur/socialnetwork_web
    ports:
      - "5050:80"
    depends_on:
      - rabbitmq
    restart: on-failure


    
  worker:
    image: retur/socialnetwork_worker
    ports:
      - "8080:5000"
    depends_on:
      - rabbitmq
    restart: on-failure

